services:
  app:
    restart: always
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx/dev
  #   ports:
  #     - 80:80
  #     - 443:443
